name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository using git
        run: |
          pacman -Sy git sudo docker docker-compose --noconfirm
          git clone --recurse-submodules https://github.com/${{ github.repository }} StratOS-iso

      - name: Build and Release ISO
        run: |
          cd StratOS-iso
          sudo docker compose down && docker compose up