name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository using git
        run: |
          sudo apt -y update
          # sudo apt install -y docker-compose-plugin # docker compose has become part of Docker
          git clone --recurse-submodules https://github.com/${{ github.repository }} StratOS-iso

      - name: Build and Release ISO
        run: |
          cd StratOS-iso
          sudo docker compose down && docker compose up